apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: big-data
build:
  artifacts:
  - image: bigdata-spark
    context: Spark
    docker:
      dockerfile: Dockerfile
  - image: bigdata-webapp
    context: k8s-app
    docker:
      dockerfile: Dockerfile
  - image: python-kafka-publisher-demo
    context: kafka_prod/python-publisher
  - image: python-kafka-subscriber-demo
    context: kafka_prod/python-subscriber

deploy:
  helm:
    releases:
    - name: kafka-chart
      chartPath: ./helm-strimzi/strimzi-kafka-operator/
    #- name: hdfs-chart
    #  chartPath: ./helm-hdfs/hadoop/
    #  namespace: default
    #  setValues: 
    #    hdfs.dataNode.replicas: 1 
    #    yarn.nodeManager.replicas: 1 
    #    hdfs.webhdfs.enabled: true
  kubectl:
    manifests:
    - k8s-app/db_mysql.yaml
    - k8s-app/memcached.yaml
    #- k8s-app/spark.yaml
    - k8s-app/webapp.yaml
    - k8s-app/strimzi_cluster.yaml
    # - k8s-app/kafka_topic.yml  
    #- kafka_prod/python-publisher/k8s/*
    #- kafka_prod/python-subscriber/k8s/*

