apiVersion: apps/v1
kind: Deployment
metadata:

  name: database
  labels:
    app: my-database
spec:
  # A single mysql instance
  replicas: 1
  selector:
    matchLabels:
      app: my-mysql
  template:
    metadata:
      labels:
        app: my-mysql
    spec:
      # Use the init container to download data to the location where the mysql container expects it
      initContainers:
        - name: init-container-data-downloader
          image: curlimages/curl
          args:
            - "-o"
            - "/tmp/data/init.sql" # we are saving downloaded file as init.sql in /tmp/data directory
            - "https://pastebin.com/dl/bNQMsab9"
          volumeMounts:
            - name: data-volume
              mountPath: /tmp/data
      # The actual mysql database
      containers:
        - name: my-mysql
          image: mysql

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysecretpw"
            - name: MYSQL_DATABASE
              value: "sportsdb"

          volumeMounts:
            - name: data-volume
              mountPath: /docker-entrypoint-initdb.d/



          ports:
            - containerPort: 3306
            - containerPort: 33060
          livenessProbe:
            tcpSocket:
              port: 33060
            initialDelaySeconds: 300 # 
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 33060
            initialDelaySeconds: 5
            periodSeconds: 10

      volumes:
        - name: data-volume
          emptyDir: {}







 CaseNumber, Date, Block, IUCR, PrimaryType, Description, LocationDescription, Arrest, Domestic, Beat, District, Ward, CommunityArea, FBICode, XCoordinate, YCoordinate, Year, UpdatedOn, Latitude, Longitude, Location

 ,'JA117989','01/16/2017 02:45:00 PM','033XX W OGDEN AVE','0880','THEFT','PURSE-SNATCHING','SIDEWALK','False','False',1021,'10.0','24.0','29.0','06',NULL,NULL,2017,'01/23/2017 03:52:03 PM',NULL,NULL,NULL