apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic 
metadata:
  name: crime-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
status:
  conditions: 
  - status: "True"
    type: Ready
  observedGeneration: 1
