apiVersion: v1
kind: Service
metadata:
  name: bigdata-webapp-service
spec:
  selector:
    app: bigdata-webapp
  ports:
  - protocol: "TCP"
    port: 5050
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigdata-webapp
spec:
  selector:
    matchLabels:
      app: bigdata-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: bigdata-webapp
    spec:
      containers:
      - name: bigdata-webapp
        image: bigdata-webapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
