apiVersion: skaffold/v2alpha4
kind: Config
build:
  artifacts:
    - image: python-kafka-publisher-demo
      context: python-publisher
    - image: python-kafka-subscriber-demo
      context: python-subscriber

deploy:
  kubectl:
    manifests:
      - ./python-publisher/k8s/*
      - ./python-subscriber/k8s/*
